general {
    col.active_border = rgb(7c3aed) rgb(06b6d4) 45deg
    col.inactive_border = rgb(1e1b4b)
    border_size = 2
    gaps_in = 5
    gaps_out = 10
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 8
        passes = 2
    }
}

exec-once = ~/.config/hypr/autostart.sh
exec-once = ~/.config/hypr/battery-alert.sh
exec-once = waybar > /dev/null 2>&1
exec-once = mako
exec-once = gsettings set org.gnome.desktop.interface gtk-the>
exec-once = gsettings set org.gnome.desktop.interface color-s>

bind = SUPER, W, exec, bash /home/development/...
bind = , code:107, exec, bash /home/development/...
bind = , Print, exec, seu_comando_aqui && sync
bind = SUPER SHIFT, S, exec, seu_outro_comando_aqui && sync
bind = $mainMod, SPACE, exec, wofi --show drun

env = GTK_THEME,Arc-Dark
env = QT_QPA_PLATFORMTHEME,qt6ct
env = MOZ_ENABLE_WAYLAND,1
env = MOZ_USE_XINPUT2,1
